---
label: Site
hide_body: true
fields:
- type: text
  name: name
  label: name
- type: text
  name: fonts
  label: fonts
- type: file
  name: image_url
  label: image_url
- type: text
  name: link
  label: link
