---
label: Site
hide_body: true
fields:
- type: text
  name: name
  label: name
- type: text
  name: fonts
  label: fonts
- type: file
  name: image_url
  label: image_url
- type: text
  name: link
  label: link
pages:
- src/sites/ashx-video.md
- src/sites/deplace-maison.md.md
- src/sites/editions-jordan-sowers.md
- src/sites/the-outline.md
